services:
  - type: web
    name: render-socket
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
